name             'goapp'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures goapp'
long_description 'Installs/Configures goapp'
version          '0.1.0'
